# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('note', models.TextField()),
                ('gender', models.BooleanField(default=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
